# pulled from repo
name: "shellcheck"

on:
  push:
    branches: [ $default-branch, $protected-branches ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install shellcheck
        run: sudo snap install shellcheck

      - name: Place up config functions file
        run: sudo cp lib/up-config.functions /usr/local/lib/up-config.functions

      - name: Check up-config installer
        run: shellcheck install.sh

      - name: Check up-config
        run: shellcheck -x lib/up-config