name: "shellcheck"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install shellcheck
        run: sudo snap install shellcheck

      - name: Place up-config lib file
        run: sudo cp lib/up-config.functions /usr/local/lib/up-config.functions

      - name: Place up-config file
        run: sudo cp lib/up-config /usr/local/bin/up-config

      - name: Check up-config lib file
        run: ls -lah /usr/local/lib/up-config.functions
        
      - name: Check up-config installer
        run: shellcheck install.sh

      - name: Check up-config
        run: shellcheck -x /usr/local/bin/up-config
